In [1]:
import numpy as np 
import pandas as pd 
from sklearn.model_selection import train_test_split

In [6]:
email_train = pd.read_csv("emails_train.csv")
email_train

,Email No.,the,to,ect,and,for,of,a,you,hou,...,connevey,jay,valued,lay,infrastructure,military,allowing,ff,dry,Prediction
0,Email 1,0,0,1,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Email 2,8,13,24,6,6,2,102,1,27,...,0,0,0,0,0,0,0,1,0,0
2,Email 3,0,0,1,0,0,0,8,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Email 4,0,5,22,0,5,1,51,2,10,...,0,0,0,0,0,0,0,0,0,0
4,Email 5,7,6,17,1,5,2,57,0,9,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3993,Email 3994,0,2,1,1,0,1,14,0,0,...,0,0,0,0,0,0,0,0,0,1
3994,Email 3995,18,8,1,5,3,1,81,0,1,...,0,0,0,0,0,0,0,0,0,0
3995,Email 3996,6,3,15,2,7,1,67,4,6,...,0,0,0,0,0,0,0,2,0,0
3996,Email 3997,4,1,4,4,2,0,26,2,2,...,0,0,0,0,0,0,0,0,0,0
3997,Email 3998,2,1,1,1,1,0,9,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
email_test = pd.read_csv("emails_test.csv")
email_test

,Email No.,the,to,ect,and,for,of,a,you,hou,...,connevey,jay,valued,lay,infrastructure,military,allowing,ff,dry,Prediction
0,Email 4000,2,1,1,1,1,0,9,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Email 4001,0,2,2,0,0,1,40,1,0,...,0,0,0,0,0,0,0,1,0,1
2,Email 4002,11,4,1,6,1,3,75,3,3,...,0,0,0,0,0,0,0,1,0,0
3,Email 4003,0,5,2,0,2,0,18,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Email 4004,0,0,1,0,0,0,22,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1168,Email 5168,2,2,2,3,0,0,32,0,0,...,0,0,0,0,0,0,0,0,0,0
1169,Email 5169,35,27,11,2,6,5,151,4,3,...,0,0,0,0,0,0,0,1,0,0
1170,Email 5170,0,0,1,1,0,0,11,0,0,...,0,0,0,0,0,0,0,0,0,1
1171,Email 5171,2,7,1,0,2,1,28,2,0,...,0,0,0,0,0,0,0,1,0,1
1172,Email 5172,22,24,5,1,6,5,148,8,2,...,0,0,0,0,0,0,0,0,0,0

In [18]:
import pandas as pd
df= pd.read_csv('emails_train.csv')
df= df.drop(labels= ['Prediction'], axis= 1)
d={}
n=len(df)
no_yes=0
no_no=0
def yes_count(s,l):
    c=0
    for i in range(n):
        if(df[l][i]==s and df['Prediction'][i]==1):
            c=c+1
    return c
def no_count(s,l):
    c = 0
    for i in range(n):
        if (df[l][i] == s and df['Prediction'][i] == 0):
            c = c + 1
    return c
for i in range(len(df)):
    if(df['Prediction'][i]==1):
        no_yes=no_yes+1
no_no=3998-no_yes
for k in list(df)[1:]:
    d1={}
    for j in df[k].unique():
          l=[yes_count(j,k)/no_yes,no_count(j,k)/no_no]
          d1[j]=l
    d[k]=d1
testDS= pd.read_csv('emails_test.csv')
acc = 0
for test in range(len(testDS)):
    w=[]
    for i in range(0,1172):
        w.append(testDS.iloc[test,i])
    z=0
    probability_yes= (no_yes/n)
    for i in range(1172):
        probability_yes=probability_yes*d[list(df)[1:][i]][w[i]][0]
    probability_no= (no_no/n)
    for i in range(1172):
        probability_no=probability_no*d[list(df)[1:][i]][w[i]][1]
    print("Probability of yes : "+str(probability_yes),"Probability of No : "+str(probability_no))
    if(probability_yes>probability_no):
        print("The value of play is Yes")
        if(testDS.iloc[test,1172]==1):
            acc = acc + 1
    else:
        print("The value of play is No")
        if(testDS.iloc[test,1172]==0):
            acc = acc + 1
acc = (acc/len(testDS))*100
print("Total accuracy = " + str(acc))

KeyError: 'Prediction'