In [1]:
import numpy as np 
import pandas as pd 
from sklearn.model_selection import train_test_split

In [2]:
email_train = pd.read_csv("emails_train.csv")
email_train

,Email No.,the,to,ect,and,for,of,a,you,hou,...,connevey,jay,valued,lay,infrastructure,military,allowing,ff,dry,Prediction
0,Email 1,0,0,1,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Email 2,8,13,24,6,6,2,102,1,27,...,0,0,0,0,0,0,0,1,0,0
2,Email 3,0,0,1,0,0,0,8,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Email 4,0,5,22,0,5,1,51,2,10,...,0,0,0,0,0,0,0,0,0,0
4,Email 5,7,6,17,1,5,2,57,0,9,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3993,Email 3994,0,2,1,1,0,1,14,0,0,...,0,0,0,0,0,0,0,0,0,1
3994,Email 3995,18,8,1,5,3,1,81,0,1,...,0,0,0,0,0,0,0,0,0,0
3995,Email 3996,6,3,15,2,7,1,67,4,6,...,0,0,0,0,0,0,0,2,0,0
3996,Email 3997,4,1,4,4,2,0,26,2,2,...,0,0,0,0,0,0,0,0,0,0
3997,Email 3998,2,1,1,1,1,0,9,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
email_test = pd.read_csv("emails_test.csv")
email_test

,Email No.,the,to,ect,and,for,of,a,you,hou,...,connevey,jay,valued,lay,infrastructure,military,allowing,ff,dry,Prediction
0,Email 4000,2,1,1,1,1,0,9,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Email 4001,0,2,2,0,0,1,40,1,0,...,0,0,0,0,0,0,0,1,0,1
2,Email 4002,11,4,1,6,1,3,75,3,3,...,0,0,0,0,0,0,0,1,0,0
3,Email 4003,0,5,2,0,2,0,18,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Email 4004,0,0,1,0,0,0,22,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1168,Email 5168,2,2,2,3,0,0,32,0,0,...,0,0,0,0,0,0,0,0,0,0
1169,Email 5169,35,27,11,2,6,5,151,4,3,...,0,0,0,0,0,0,0,1,0,0
1170,Email 5170,0,0,1,1,0,0,11,0,0,...,0,0,0,0,0,0,0,0,0,1
1171,Email 5171,2,7,1,0,2,1,28,2,0,...,0,0,0,0,0,0,0,1,0,1
1172,Email 5172,22,24,5,1,6,5,148,8,2,...,0,0,0,0,0,0,0,0,0,0

In [4]:
import pandas as pd
import numpy as np
import math
import csv
import pdb

In [5]:
#reading the dataset
def read_data(filename):

    with open(filename,'r') as csvfile:
        datareader = csv.reader(csvfile)
        metadata = next(datareader)
        traindata=[]
        for row in datareader:
            traindata.append(row)

    return (metadata, traindata)

In [6]:
#splitting the data into training and testing
def splitDataset(dataset, splitRatio):
    trainSize = int(len(dataset) * splitRatio)
    trainSet = []
    testset = list(dataset)
    i=0
    while len(trainSet) < trainSize:
        trainSet.append(testset.pop(i))
    return [trainSet, testset]

In [7]:
#classifying the data 
def classify(data,test):

    total_size = data.shape[0]
    print("\n")
    print("Size of training data=",total_size) # total size of the training set
    print("Size of test data=",test.shape[0]) # test size of the training set

    total_yes = 0
    total_no = 0
    prob_yes = 0
    prob_no = 0
    print("\n")
    print("[0-not spam \t 1-spam]")
    print("Target Total count [0/1] Probability")

    for x in range(data.shape[0]):
        if data[x,data.shape[-1]-1] == '1':
            total_yes +=1
        if data[x,data.shape[-1]-1] == '0':
            total_no +=1

    prob_yes=total_yes/total_size
    prob_no= total_no / total_size

    print('1',"\t",total_yes,"\t",prob_yes)
    print('0',"\t",total_no,"\t",prob_no)


    prob0 =np.zeros((test.shape[1]-1))
    prob1 =np.zeros((test.shape[1]-1))
    accuracy=0
    print("\n")
    print("Email Prediction(NB) Actual Target")

    for t in range(test.shape[0]):
        for k in range (test.shape[1]-1):
            count1=count0=0
            for j in range (data.shape[0]):
                #how many times appeared with no
                if test[t,k] == data[j,k] and data[j,data.shape[1]-1]== '0':
                    count0+=1
                #how many times appeared with yes
                if test[t,k]==data[j,k] and data[j,data.shape[1]-1]=='1':
                    count1+=1
            prob0[k]=count0/total_no
            prob1[k]=count1/total_yes

        prob_no=prob_no
        prob_yes=prob_yes
        for i in range(test.shape[1]-1):
            prob_no=prob_no*prob0[i]
            prob_yes=prob_yes*prob1[i]
        if prob_no>prob_yes:
            predict=0
        else:
            predict=1

        print(t+1,"\t",predict,"\t    ",test[t,test.shape[1]-1])
        if predict == test[t,test.shape[1]-1]:
            accuracy+=1
    final_accuracy=(accuracy/test.shape[0])*100
    print("accuracy",final_accuracy,"%")
    return

metadata,traindata= read_data("emails.csv")
splitRatio=0.99
trainingset, testset=splitDataset(traindata, splitRatio)
training=np.array(trainingset)
testing=np.array(testset)
classify(training,testing)

Size of training data= 5120
Size of test data= 52


[0-not spam 	 1-spam]
Target Total count [0/1] Probability
1 	 1484 	 0.28984375
0 	 3636 	 0.71015625


Email Prediction(NB) Actual Target
1 	 1 	     0
2 	 1 	     0
3 	 1 	     1
4 	 1 	     0
5 	 1 	     0
6 	 1 	     0
7 	 1 	     0
8 	 1 	     1
9 	 1 	     0
10 	 1 	     0
11 	 1 	     0
12 	 1 	     1
13 	 1 	     0
14 	 1 	     0
15 	 1 	     0
16 	 1 	     1
17 	 1 	     0
18 	 1 	     1
19 	 1 	     0
20 	 1 	     0
21 	 1 	     0
22 	 1 	     0
23 	 1 	     1
24 	 1 	     0
25 	 1 	     1
26 	 1 	     0
27 	 1 	     0
28 	 1 	     0
29 	 1 	     0
30 	 1 	     0
31 	 1 	     0
32 	 1 	     0
33 	 1 	     0
34 	 1 	     1
35 	 1 	     1
36 	 1 	     0
37 	 1 	     1
38 	 1 	     0
39 	 1 	     0
40 	 1 	     1
41 	 1 	     0
42 	 1 	     0
43 	 1 	     1
44 	 1 	     1
45 	 1 	     0
46 	 1 	     0
47 	 1 	     1
48 	 1 	     0
49 	 1 	     0
50 	 1 	     1
51 	 1 	     1
52 	 1 	     0
accuracy 0.0 %

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

nb = MultinomialNB()
nb.fit(trainSet, testset)
plot_confusion_matrix(nb,trainSet, testset)
print(classification_report(preds,y_test))

NameError: name 'trainSet' is not defined