In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as snsb

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression

%matplotlib inline


dataset = pd.DataFrame(pd.read_csv("features.csv"))
dataset.head()
dataset.shape
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             101 non-null    int64
 1   area              101 non-null    int64
 2   bedrooms          101 non-null    int64
 3   bathrooms         101 non-null    int64
 4   stories           101 non-null    int64
 5   mainroad          101 non-null    object
 6   guestroom         101 non-null    object
 7   basement          101 non-null    object
 8   hotwaterheating   101 non-null    object
 9   airconditioning   101 non-null    object
 10  parking           101 non-null    int64
 11  prefarea          101 non-null    object
 12  furnishingstatus  101 non-null    object
dtypes: int64(6), object(7)
memory usage: 10.4+ KB

In [3]:
housefeatures =  ['mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning', 'prefarea']

def binary_map(x):
    return x.map({'yes': 1, "no": 0})

In [4]:
dataset[housefeatures] = dataset[housefeatures].apply(binary_map)
dataset.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,5950000,6420,3,1,1,1,0,1,0,1,0,1,furnished
1,5950000,7020,3,1,1,1,0,1,0,1,2,1,semi-furnished
2,5950000,6540,3,1,1,1,1,1,0,0,2,1,furnished
3,5950000,7231,3,1,2,1,1,1,0,1,0,1,semi-furnished
4,5950000,6254,4,2,1,1,0,1,0,0,1,1,semi-furnished

In [6]:
dataset.drop(['furnishingstatus'], axis = 1, inplace = True)
dataset.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea
0,5950000,6420,3,1,1,1,0,1,0,1,0,1
1,5950000,7020,3,1,1,1,0,1,0,1,2,1
2,5950000,6540,3,1,1,1,1,1,0,0,2,1
3,5950000,7231,3,1,2,1,1,1,0,1,0,1
4,5950000,6254,4,2,1,1,0,1,0,0,1,1

In [7]:
np.random.seed(0)
df_train, df_test = train_test_split(dataset, train_size = 0.65, test_size = 0.35, random_state = 100)

In [8]:
scaler = MinMaxScaler()

In [9]:
housefeatures2 = ['area', 'bedrooms', 'bathrooms', 'stories', 'parking','price']
y_train = df_train.pop('price')
X_train = df_train

In [10]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression

lm = LinearRegression()
lm.fit(X_train, y_train)

rfe = RFE(lm, n_features_to_select=6, step=1)
rfe = rfe.fit(X_train, y_train)

In [11]:
list(zip(X_train.columns,rfe.support_,rfe.ranking_))

[('area', False, 6),
 ('bedrooms', True, 1),
 ('bathrooms', False, 4),
 ('stories', True, 1),
 ('mainroad', True, 1),
 ('guestroom', False, 3),
 ('basement', False, 5),
 ('hotwaterheating', True, 1),
 ('airconditioning', False, 2),
 ('parking', True, 1),
 ('prefarea', True, 1)]

In [19]:
#X values and Predicted Y value
#Scatter Plot with Regression Line
num_features = ['area','stories', 'bathrooms', 'airconditioning', 'prefarea','parking','price']
df_train[num_features] = scaler.fit_transform(df_train[num_features])
y_train = df_train.pop('price')
X_train = df_train
X_train = sm.add_constant(X_train)
X_train_rfe = X_train[X_train_rfe.columns]

y_pred = lm.predict(X_train_rfe)
print("X Values:")
print(X_train_rfe)
print("Predictions:")
print(y_pred)

KeyError: "['price'] not in index"

In [ ]:
fig = plt.figure()
plt.scatter(y_test,y_pred)
fig.suptitle('y_test vs y_pred', fontsize=22)             
plt.xlabel('y_test', fontsize=20) 
plt.ylabel('y_pred', fontsize=18)   
m, g = np.polyfit(y_test, y_pred, 1)
plt.plot(y_test, m*y_test + g,'b')